envname: HuskyNavigateEnv
model_id: space7
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 4.71]
initial_pos: [-14.3, 5, 1.2]
fov: 1.
is_discrete: false

use_filler: false
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, rgb_filled, depth, normal, semantics]
resolution: 256

speed:
  timestep: 0.001
  frameskip: 1

mode: webgui #gui|headless
verbose: false
semantic_source: 1 # 2D3DS
semantic_color: 1  # random
